# docker-compose.yml — основной файл для запуска проекта в продакшен:

# Определяет сервис app, который будет собран из Dockerfile
# Настраивает порты и переменные окружения для продакшена

version: '3.8'

services:
  app:
    build: . # указывает Dockerfile для сборки
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
