version: '3.8'

services:
  app-dev: # Сервис разработки
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    environment: # Переменные окружения
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
      - MONGO_URI=mongodb://admin:password@mongodb:27017 # указывает URI для подключения к MongoDB
      - MONGO_DB=logs # указывает имя базы данных для MongoDB
      - REDIS_HOST=redis # указывает хост Redis
      - REDIS_PORT=6379 # указывает порт Redis
      - REDIS_PASSWORD=321321 # указывает пароль Redis
    depends_on: # Зависимость от сервиса db
      - db
      - mongodb
      - redis
    command: yarn start:dev # Команда для запуска приложения в режиме разработки
  mongodb:
    image: mongo:latest
    container_name: nest-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    restart: always

  redis-insight: # не работает через браузер
    image: redis/redisinsight:latest
    ports:
      - '8002:8001'
    volumes:
      - redis-insight-data:/db
    restart: always
    depends_on:
      - redis

  db: # Сервис базы данных
    image: postgres:14-alpine # Используем образ Postgres
    ports:
      - '5433:5432' # Порт для доступа к базе данных
    environment: # Переменные окружения
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    volumes:
      - postgres_data:/var/lib/postgresql/data # Волюм для хранения данных базы данных
    restart: always

  pgadmin: # Сервис pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment: # Переменные окружения
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on: # Зависимость от сервиса db
      - db
    restart: always # Перезапуск сервиса при изменении

volumes: # Волюмы для хранения данных баз данных
  postgres_data: # сохраняет данные Postgres
  mongodb_data: # сохраняет данные MongoDB
  redis-data: # сохраняет данные Redis
  redis-insight-data: # сохраняет данные RedisInsight
